<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Registration;

class RegistrationSeeder extends Seeder
{
    public function run(): void
    {
        $dummy = [
            [
                'nama' => 'Ahmad Fauzi',
                'nik' => '1234567890123456',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2012-01-01',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'nama_ayah' => 'Budi Fauzi',
                'nama_ibu' => 'Siti Aminah',
                'pekerjaan_ayah' => 'Karyawan',
                'penghasilan_ayah' => '2.000.000-4.999.999',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '1.000.000-1.999.999',
                'alamat' => 'Jl. Merdeka No. 1',
                'telepon_ortu' => '081234567890',
                'jadwal_abk' => '2025-08-01',
                'status_lolos' => 1,
                'status_pip' => 'Y',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 7,
                'interaksi' => 8,
                'tes_baca_tulis' => 9,
                'abk' => 6,
                'total_poin' => 30,
            ],
            [
                'nama' => 'Dewi Lestari',
                'nik' => '1234567890123457',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2012-02-02',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'nama_ayah' => 'Slamet Riyadi',
                'nama_ibu' => 'Sri Lestari',
                'pekerjaan_ayah' => 'Wiraswasta',
                'penghasilan_ayah' => '>=5.000.000',
                'pekerjaan_ibu' => 'Guru',
                'penghasilan_ibu' => '2.000.000-4.999.999',
                'alamat' => 'Jl. Sudirman No. 2',
                'telepon_ortu' => '081234567891',
                'jadwal_abk' => '2025-08-02',
                'status_lolos' => 1,
                'status_pip' => 'N',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 8,
                'interaksi' => 7,
                'tes_baca_tulis' => 8,
                'abk' => 7,
                'total_poin' => 30,
            ],
            [
                'nama' => 'Budi Santoso',
                'nik' => '1234567890123458',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2012-03-03',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Kristen',
                'nama_ayah' => 'Sutrisno',
                'nama_ibu' => 'Yuniarti',
                'pekerjaan_ayah' => 'Petani',
                'penghasilan_ayah' => '<1.000.000',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '<1.000.000',
                'alamat' => 'Jl. Pahlawan No. 3',
                'telepon_ortu' => '081234567892',
                'jadwal_abk' => '2025-08-03',
                'status_lolos' => 0,
                'status_pip' => 'Y',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 5,
                'interaksi' => 6,
                'tes_baca_tulis' => 5,
                'abk' => 4,
                'total_poin' => 20,
            ],
            [
                'nama' => 'Citra Ayu',
                'nik' => '1234567890123459',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2012-04-04',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'nama_ayah' => 'Hendro',
                'nama_ibu' => 'Rina',
                'pekerjaan_ayah' => 'PNS',
                'penghasilan_ayah' => '2.000.000-4.999.999',
                'pekerjaan_ibu' => 'PNS',
                'penghasilan_ibu' => '2.000.000-4.999.999',
                'alamat' => 'Jl. Diponegoro No. 4',
                'telepon_ortu' => '081234567893',
                'jadwal_abk' => '2025-08-04',
                'status_lolos' => 1,
                'status_pip' => 'N',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 9,
                'interaksi' => 8,
                'tes_baca_tulis' => 9,
                'abk' => 8,
                'total_poin' => 34,
            ],
            [
                'nama' => 'Eka Putra',
                'nik' => '1234567890123460',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-05-05',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'nama_ayah' => 'Slamet',
                'nama_ibu' => 'Sulastri',
                'pekerjaan_ayah' => 'Buruh',
                'penghasilan_ayah' => '1.000.000-1.999.999',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '<1.000.000',
                'alamat' => 'Jl. Malioboro No. 5',
                'telepon_ortu' => '081234567894',
                'jadwal_abk' => '2025-08-05',
                'status_lolos' => 0,
                'status_pip' => 'Y',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 4,
                'interaksi' => 5,
                'tes_baca_tulis' => 4,
                'abk' => 3,
                'total_poin' => 16,
            ],
            [
                'nama' => 'Fajar Sidik',
                'nik' => '1234567890123461',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2012-06-06',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'nama_ayah' => 'Samsul',
                'nama_ibu' => 'Nuraini',
                'pekerjaan_ayah' => 'Sopir',
                'penghasilan_ayah' => '1.000.000-1.999.999',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '<1.000.000',
                'alamat' => 'Jl. Gatot Subroto No. 6',
                'telepon_ortu' => '081234567895',
                'jadwal_abk' => '2025-08-06',
                'status_lolos' => 1,
                'status_pip' => 'N',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 6,
                'interaksi' => 7,
                'tes_baca_tulis' => 6,
                'abk' => 5,
                'total_poin' => 24,
            ],
            [
                'nama' => 'Gita Prameswari',
                'nik' => '1234567890123462',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '2012-07-07',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Hindu',
                'nama_ayah' => 'Wayan',
                'nama_ibu' => 'Ayu',
                'pekerjaan_ayah' => 'Seniman',
                'penghasilan_ayah' => '2.000.000-4.999.999',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '1.000.000-1.999.999',
                'alamat' => 'Jl. Kuta No. 7',
                'telepon_ortu' => '081234567896',
                'jadwal_abk' => '2025-08-07',
                'status_lolos' => 1,
                'status_pip' => 'N',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 7,
                'interaksi' => 8,
                'tes_baca_tulis' => 7,
                'abk' => 6,
                'total_poin' => 28,
            ],
            [
                'nama' => 'Hana Putri',
                'nik' => '1234567890123463',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2012-08-08',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'nama_ayah' => 'Rahmat',
                'nama_ibu' => 'Sari',
                'pekerjaan_ayah' => 'Nelayan',
                'penghasilan_ayah' => '1.000.000-1.999.999',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '<1.000.000',
                'alamat' => 'Jl. Pantai Losari No. 8',
                'telepon_ortu' => '081234567897',
                'jadwal_abk' => '2025-08-08',
                'status_lolos' => 0,
                'status_pip' => 'Y',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 3,
                'interaksi' => 4,
                'tes_baca_tulis' => 3,
                'abk' => 2,
                'total_poin' => 12,
            ],
            [
                'nama' => 'Indra Gunawan',
                'nik' => '1234567890123464',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2012-09-09',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'nama_ayah' => 'Gunawan',
                'nama_ibu' => 'Dewi',
                'pekerjaan_ayah' => 'Pedagang',
                'penghasilan_ayah' => '2.000.000-4.999.999',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '1.000.000-1.999.999',
                'alamat' => 'Jl. Ampera No. 9',
                'telepon_ortu' => '081234567898',
                'jadwal_abk' => '2025-08-09',
                'status_lolos' => 1,
                'status_pip' => 'N',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 6,
                'interaksi' => 7,
                'tes_baca_tulis' => 6,
                'abk' => 5,
                'total_poin' => 24,
            ],
            [
                'nama' => 'Joko Susilo',
                'nik' => '1234567890123465',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '2012-10-10',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'nama_ayah' => 'Sukamto',
                'nama_ibu' => 'Sukesi',
                'pekerjaan_ayah' => 'Guru',
                'penghasilan_ayah' => '2.000.000-4.999.999',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '1.000.000-1.999.999',
                'alamat' => 'Jl. Slamet Riyadi No. 10',
                'telepon_ortu' => '081234567899',
                'jadwal_abk' => '2025-08-10',
                'status_lolos' => 1,
                'status_pip' => 'N',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 8,
                'interaksi' => 9,
                'tes_baca_tulis' => 8,
                'abk' => 7,
                'total_poin' => 32,
            ],
            [
                'nama' => 'Kiki Amelia',
                'nik' => '1234567890123466',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2012-11-11',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'nama_ayah' => 'Amir',
                'nama_ibu' => 'Aisyah',
                'pekerjaan_ayah' => 'Karyawan',
                'penghasilan_ayah' => '2.000.000-4.999.999',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '1.000.000-1.999.999',
                'alamat' => 'Jl. Pajajaran No. 11',
                'telepon_ortu' => '081234567900',
                'jadwal_abk' => '2025-08-11',
                'status_lolos' => 1,
                'status_pip' => 'Y',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 7,
                'interaksi' => 8,
                'tes_baca_tulis' => 7,
                'abk' => 6,
                'total_poin' => 28,
            ],
            [
                'nama' => 'Lina Marlina',
                'nik' => '1234567890123467',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2012-12-12',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'nama_ayah' => 'Marlina',
                'nama_ibu' => 'Siti',
                'pekerjaan_ayah' => 'Wiraswasta',
                'penghasilan_ayah' => '>=5.000.000',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '2.000.000-4.999.999',
                'alamat' => 'Jl. Siliwangi No. 12',
                'telepon_ortu' => '081234567901',
                'jadwal_abk' => '2025-08-12',
                'status_lolos' => 0,
                'status_pip' => 'N',
                'file_kk' => null,
                'file_akta' => null,
                'nama_wali' => null,
                'alamat_wali' => null,
                'no_telp_wali' => null,
                'pekerjaan_wali' => null,
                'tes_warna' => 2,
                'interaksi' => 3,
                'tes_baca_tulis' => 2,
                'abk' => 1,
                'total_poin' => 8,
            ],
        ];
        foreach ($dummy as $data) {
            Registration::create($data);
        }
    }
}
